# Generated by Django 4.1.2 on 2022-11-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
    ]
