# Generated by Django 4.1.2 on 2022-11-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='ac_holder_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='ac_number',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='ifsc',
        ),
    ]
